{
  "services": [
    "docker",
    "postgresql",
  ],
  "sudo": "required",
  "before_install": [
    "openssl aes-256-cbc -K $encrypted_d303290e7d32_key -iv $encrypted_d303290e7d32_iv -in keys/id_rsa_observatory_extension.key.enc -out keys/id_rsa_observatory_extension.key -d"
  ],
  "script": "make travis-etl-unittest",
  "addons": {
    "postgresql": "9.5",
  },
  "install": [
    "sudo apt-get install -y postgresql-9.5-postgis-2.3",
    "sudo service postgresql restart"
  ]
  "notifications": {
    "webhooks": {
      "urls": [
        "http://build.openscrape.com/api/v1/travis/notify"
      ],
      "on_success": "always",
      "on_failure": "always",
      "on_start": "always",
      "on_cancel": "always",
      "on_error": "always"
    }
  }
}
